Rewrite the js part to ts
PIVX-Labs/pivx-shield pull request #67
Opened 2023-11-09 10:19 UTC by Duddino

This also fixes a couple of bugs.
Draft because it needs a bit more testing

2023-11-11 13:32 UTC, panleone requested changes
tACK, working as expected just some small nits

2023-11-11 13:32 UTC, panleone commented on js/pivx_shield.ts
> +  save() {
can remove {string} from @returns since we are on ts

2023-11-11 13:32 UTC, panleone commented on js/pivx_shield.ts
> +   * @param {string[]} nullifiers - Array of nullifiers
can remove string[] from JSDoc since we are on ts

2023-11-11 13:32 UTC, panleone commented on js/pivx_shield.ts
> +  async createTransaction({
use ts instead of specifying types with JSDoc

2023-11-11 13:32 UTC, panleone commented on js/pivx_shield.ts
> +  static async create({
same here I guess

2023-11-22 10:12 UTC, Duddino commented on js/pivx_shield.ts
> +  static async create({
These are for commenting not for types

2023-11-28 19:37 UTC, merged