Store all nullifiers belonging to the wallet
PIVX-Labs/pivx-shield pull request #81
Opened 2024-03-06 18:03 UTC by panleone

Store in memory all nullifiers belonging to the wallet, so it's possible to decrypt a shieldSpend only from its nullifier.
This PR is needed to implement the shield activity on MPW

2024-10-07 08:29 UTC, Duddino requested changes

2024-10-07 08:29 UTC, Duddino commented on js/pivx_shield.ts
> +      Object.entries(shieldData.mapNullifierNote),
This needs to handle being undefined
```suggestion
      Object.entries(shieldData.mapNullifierNote ?? {}),
```

2024-10-07 08:29 UTC, Duddino commented on js/pivx_shield.ts
>        shieldData.lastProcessedBlock,
We need sync from scratch if mapNullifierNote is undefined or old wallets won't have the complete activity

2024-10-07 08:29 UTC, Duddino commented on src/transaction.rs
> +) -> Result<JsValue, JsValue> {
needs a test

2024-10-11 11:31 UTC, Duddino approved these changes
utACK, clear to merge when PIVX-Labs/MyPIVXWallet#416 gets approved as well

2024-10-14 08:59 UTC, panleone commented
rebased to get rid of the git merge commit. You can check that the diff is trivial with

`git diff 438fb04`

and check the files modified by this PR

2024-10-19 11:35 UTC, merged